# -*- coding:utf-8 -*-
print('hello,world')
print('table')
print ('happy')
print('ok')
print ('what')
print ('why')
print('hao')
print('ooo')
print('when')
print ('water')
print('haha')
print('phone')
